<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Marcel - Backoffice</title>
<?php echo $this->headMeta() ?>
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/back.css" type="text/css" />
<!--
widget, a free CSS web template by spyka Webmaster (www.spyka.net)

Download: http://www.spyka.net/web-templates/widget/

License: Creative Commons Attribution
//-->
</head>

<body class="noheader">
<div id="container">
	<div id="header">
    	<h1><a href="<?php echo $this->baseUrl() ?>/">Marcel<strong>BackOffice</strong></a></h1>
        <div class="clear"></div>
    </div>
    <div id="nav">
    	<ul class="sf-menu">
			<li><a href='#'>Login</a></li>
		</ul>
    </div>
    
     <div id="body">            
		<div id="content">
            <div class="box">
	<?php echo $this->layout()->content ?>
			</div>
        </div>
        
		<div class="clear"></div>
    </div>
</div>
	 <div id="footer">
		<div id="footer-links">
			<p>&copy; Marcel <?php echo date('Y') ?>.</p>
		</div>  
	</div>
</body>
</html>
