<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->headTitle();
			echo $this->headMeta(); ?>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('new-logo', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/new-logo/css/01.global.css" />
		<?php endif; ?>
		<link rel="icon" href="<?php echo $this->baseUrl() ?>/favicon.ico" type="image/x-icon" />
		<meta property="og:type" content="website">
		<meta property="og:title" content="<?php echo tr('EMMETT - New logo') ?>">
		<meta property="og:url" content="http://<?php echo $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']?>">
		<meta property="og:image" content="http://<?php echo $_SERVER['SERVER_NAME'] ?>/img/new-logo/logo.png">
		<meta property="og:description" content='<?php echo tr('Discover our new logo and some secret tracks...') ?>'>
	</head>
	<body>
    <div id='locale' class="later">
			<a href='<?php echo $this->url(array('lang' => 'fr')) ?>'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/lang_fr.png' /></a>
			<a href='<?php echo $this->url(array('lang' => 'en')) ?>'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/lang_en.png' /></a>
		</div>
    <div id="content">
      <div id="logo">
        <div id="innerLogo"><img src="<?php echo $this->baseUrl() ?>/img/new-logo/logo.png" /></div>
        <div id="countertext" class="later"><?php echo sprintf(tr('You have %s seconds to try something...'), '<span id="counter">30</span>') ?></div>
        <div id="typing" class="later"></div>
      </div>
		</div>
		<div id="donate" class="later">
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="Y64LAX2HZQQBJ">
				<?php if ($this->layout()->locale == 'fr') : ?>
				<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
				<?php else : ?>
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<?php endif; ?>
				<img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			</form>
		</div>
		<div id="footer" class="later">
			<a href='http://facebook.emmett.eu/' title='Facebook' target='_blank' data-tag='GO_facebook'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/facebook.png' /></a>
			<a href='http://twitter.emmett.eu/' title='Twitter' target='_blank' data-tag='GO_twitter'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/twitter.png' /></a>
			<a href='http://youtube.emmett.eu/' title='Youtube' target='_blank' data-tag='GO_youtube'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/youtube.png' /></a>
			<a href='http://soundcloud.emmett.eu/' title='SoundCloud' target='_blank' data-tag='GO_soundcloud'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/soundcloud.png' style='margin-bottom:5px;'/></a>
			<a href='http://myspace.emmett.eu/' title='MySpace' target='_blank' data-tag='GO_myspace'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/myspace.png' /></a>
			<a href='http://reverbnation.emmett.eu/' title='ReverbNation' target='_blank' data-tag='GO_reverbnation'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/reverbnation.png' style='width:55px;height:55px;margin-bottom:6px;'/></a>
			<a href='mailto:contact@emmett.eu' title='Contact' target='_blank' data-tag='GO_mail'><img src='<?php echo $this->baseUrl() ?>/img/new-logo/mail.png'  style='width:60px;height:60px;margin-bottom:2px;'/></a>
		</div>
			
		<?php if (ENVIRONMENT == 'prod') : ?>
		<script type="text/javascript" src="<?php echo $this->version('new-logo', 'js') ?>"></script>
		<?php else : ?>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/new-logo/js/01.jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/new-logo/js/02.konami.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/new-logo/js/99.init.js"></script>
		<?php endif;?>
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31404217-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
		<audio loop autoplay>
      <source src="/audio/new-logo/intro-first-aid.ogg" type="audio/ogg"/>
      <source src="/audio/new-logo/intro-first-aid.mp3" type="audio/mpeg"/>
    </audio>
	</body>
</html>
