<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->headTitle();
			echo $this->headMeta(); ?>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('new-logo', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/new-site/css/01.global.css" />
		<?php endif; ?>
		<link rel="icon" href="<?php echo $this->baseUrl() ?>/favicon.ico" type="image/x-icon" />
		<meta property="og:type" content="website">
		<meta property="og:title" content="<?php echo tr('EMMETT - New logo') ?>">
		<meta property="og:url" content="http://<?php echo $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']?>">
		<meta property="og:image" content="http://<?php echo $_SERVER['SERVER_NAME'] ?>/img/new-logo/logo.png">
		<meta property="og:description" content='<?php echo tr('Discover our new logo and some secret tracks...') ?>'>
	</head>
	<body>
		<p id="info"><?php echo tr("Sorry, we didn't take time to have this degraded version because our site is really cool on a recent browser (like <a href=\"http://www.google.com/chrome\">Chrome</a> ;))") ?></p>
	</body>
</html>