<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->headTitle();
			echo $this->headMeta(); ?>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('fighting-fate-ep', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/css/01.global.css" />
		<?php endif; ?>
		<link rel="icon" href="<?php echo $this->baseUrl() ?>/favicon.gif" type="image/gif" />
		<meta property="og:title" content="<?php echo tr('EMMETT - Fighting Fate EP') ?>">
		<meta property="og:url" content="http://<?php echo $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']?>">
		<meta property="og:image" content="http://<?php echo $_SERVER['SERVER_NAME'] ?>/img/fighting-fate-ep/cover.jpg">
		<meta property="og:description" content='<?php echo tr('Their first EP "Fighting Fate" now available on iTunes: http://goo.gl/bN9RPo') ?>'>
	</head>
	<body>
		<div id='loader'>
			<div id="bar">
				<img src="<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/loader.png" />
			</div>
			<div id="load-background"></div>
			<div id="progress"></div>
		</div>
		<div id="container"></div>
		<div id='locale' class="later">
			<a href='<?php echo $this->url(array('lang' => 'fr')) ?>' rel='nolink'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/lang_fr.png' /></a>
			<a href='<?php echo $this->url(array('lang' => 'en')) ?>' rel='nolink'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/lang_en.png' /></a>
		</div>
		<div id="fullsite" class="later">
			<h1 id="myTitle"><img src="<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/logo.png" alt="EMMETT" title="EMMETT"/></h1>
			<ul class="accordion">
				<li>
					<h4 class="atitle" id="album" data-tag="Album"><?php echo tr('Album')?></h4>
					<div class="inner">
						<ul class="endcontent">
							<li><a href="#" class="track" data-id="1" data-tag="track-intro-fighting-fate">Intro Fighting Fate &#9654;</a></li>
							<li><a href="#" class="track" data-id="2" data-tag="track-nulle-autre-ne-sait">Nulle Autre Ne Sait &#9654;</a></li>
							<li><a href="#" class="track" data-id="3" data-tag="track-surrogates">Surrogates &#9654;</a></li>
							<li><a href="#" class="track" data-id="4" data-tag="track-the-lost-identity">The Lost Identity &#9654;</a></li>
							<li><a href="#" class="track" data-id="5" data-tag="track-promises">Promises &#9654;</a></li>
							<li><a href="#" class="track" data-id="6" data-tag="track-switch-you-on">Switch You On &#9654;</a></li>
							<li><a href="#" class="track" data-id="7" data-tag="track-leaving">Leaving &#9654;</a></li>
							<li><a href="#" class="track" data-id="8" data-tag="track-fighting-fate">Fighting Fate &#9654;</a></li>
						</ul>
						<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target='_blank' style="margin-top:20px">
							<input type="hidden" name="cmd" value="_s-xclick">
							<input type="hidden" name="hosted_button_id" value="Y64LAX2HZQQBJ">
							<?php if ($this->layout()->locale == 'fr') : ?>
							<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
							<?php else : ?>
							<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
							<?php endif; ?>
							<img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
						</form>
						<span id="download"><a href="<?php echo $this->url(array('action' => 'download')) ?>" data-tag="download"><?php echo tr('Download') ?></a></span>
					</div>
				</li>
				<li>
					<h4 class="atitle band" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep'), 'band') ?>" data-tag="band"><?php echo tr('Band')?></h4>
					<div class="inner">
						<ul class="endcontent">
							<li><a href="#" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep'), 'band') ?>" id="band" class="band" data-tag="bio-band">EMMETT</a></li>
							<li><a href="#" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep', 'member' => 'cedric'), 'band') ?>" id="cedric" data-tag="cedric">Cédric</a></li>
							<li><a href="#" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep', 'member' => 'jay'), 'band') ?>" id="jay" data-tag="jay">Jay</a></li>
							<li><a href="#" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep', 'member' => 'maxime'), 'band') ?>" id="maxime" data-tag="maxime">Maxime</a></li>
							<li><a href="#" data-band="<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'fighting-fate-ep', 'member' => 'romeo'), 'band') ?>" id="romeo" data-tag="romeo">Roméo</a></li>
						</ul>
					</div>
				</li>
				<li>
					<h4 class="atitle" id="store" data-tag="Store"><?php echo tr('Store')?></h4>
					<div class="inner">
						<ul class="endcontent">
							<li><a href="http://www.amazon.com/gp/product/B00GUIYCXM/" target="_blank" data-tag="StoreAmazon">Amazon</a></li>
							<li><a href="http://www.deezer.com/album/7167652" target="_blank" data-tag="StoreDeezer">Deezer</a></li>
							<li><a href="https://itunes.apple.com/fr/album/fighting-fate/id763198261" target="_blank" data-tag="StoreItunes">iTunes</a></li>
							<li><a href="http://open.spotify.com/album/6gOEoiRvpeqTkXb4O3ntvd" target="_blank" data-tag="StoreSpotify">Spotify</a></li>
						</ul>
					</div>
				</li>
				<li>
					<h4 class="atitle" data-tag="Bonus"><?php echo tr('Misc')?></h4>
					<div class="inner">
						<ul>
							<li>
								<h5 class="atitle" data-tag="Lyrics"><?php echo tr('Lyrics')?></h5>
								<div class="inner">
									<ul class="endcontent">
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Nulle%20Autre%20Ne%20Sait.pdf" target="_blank" data-tag="Lyrics_NulleAutreNeSait">Nulle Autre Ne Sait</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Surrogates.pdf" target="_blank" data-tag="Lyrics_Surrogates">Surrogates</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/The%20Lost%20Identity.pdf" target="_blank" data-tag="Lyrics_TheLostIdentity">The Lost Identity</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Promises.pdf" target="_blank" data-tag="Lyrics_Promises">Promises</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Switch%20You%20On.pdf" target="_blank" data-tag="Lyrics_SwitchYouOn">Switch You On</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Leaving.pdf" target="_blank" data-tag="Lyrics_Leaving">Leaving</a></li>
										<li><a href="<?php echo $this->baseUrl() ?>/lyrics/fighting-fate-ep/Fighting%20Fate.pdf" target="_blank" data-tag="Lyrics_FightingFate">Fighting Fate</a></li>
									</ul>
								</div>
							</li>
							<li>
								<h5 class="atitle" data-tag="BassTab"><?php echo tr('Bass tabs')?></h5>
								<div class="inner">
									<ul class="endcontent">
										<li>Intro Fighting Fate | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Intro%20%Fighting%20Fate.gpx" target="_blank" data-tag="BassTab_Intro_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Intro%20%Fighting%20Fate.pdf" target="_blank" data-tag="BassTab_Intro_PDF">PDF</a></li>
										<li>Nulle Autre Ne Sait | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Nulle%20Autre%20Ne%20Sait.gpx" target="_blank" data-tag="BassTab_NulleAutreNeSait_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Nulle%20Autre%20Ne%20Sait.pdf" target="_blank" data-tag="BassTab_NulleAutreNeSait_PDF">PDF</a></li>
										<li>Surrogates | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Surrogates.gpx" target="_blank" data-tag="BassTab_Surrogates_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Surrogates.pdf" target="_blank" data-tag="BassTab_Surrogates_PDF">PDF</a></li>
										<li>The Lost Identity | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/The%20Lost%20Identity.gpx" target="_blank" data-tag="BassTab_TheLostIdentity_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/The%20Lost%20Identity.pdf" target="_blank" data-tag="BassTab_TheLostIdentity_PDF">PDF</a></li>
										<li>Promises | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Promises.gpx" target="_blank" data-tag="BassTab_Promises_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Promises.pdf" target="_blank" data-tag="BassTab_Promises_PDF">PDF</a></li>
										<li>Switch You On | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Switch%20You%20On.gpx" target="_blank" data-tag="BassTab_SwitchYouOn_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Switch%20You%20On.pdf" target="_blank" data-tag="BassTab_SwitchYouOn_PDF">PDF</a></li>
										<li>Leaving | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Leaving.gpx" target="_blank" data-tag="BassTab_Leaving_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Leaving.pdf" target="_blank" data-tag="BassTab_Leaving_PDF">PDF</a></li>
										<li>Fighting Fate | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Fighting%20Fate.gpx" target="_blank" data-tag="BassTab_FightingFate_GPX">GPX</a> | <a href="<?php echo $this->baseUrl() ?>/tab/fighting-fate-ep/bass/Fighting%20Fate.pdf" target="_blank" data-tag="BassTab_FightingFate_PDF">PDF</a></li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
				</li>
				<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'front') ?>' data-tag="FirstAid"><h4 class="atitle">- First Aid -</h4></a></li>
			</ul>
		</div>
		<div id="band-desc">
		</div>
		<div id='donate' class="later">
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target='_blank'>
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="Y64LAX2HZQQBJ">
				<?php if ($this->layout()->locale == 'fr') : ?>
				<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
				<?php else : ?>
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<?php endif; ?>
				<img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			</form>
		</div>
		<div id='footer' class="later">
			<a href='http://facebook.emmett.eu/' title='Facebook' target='_blank' data-tag='GO_facebook'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/facebook.png' /></a>
			<a href='http://twitter.emmett.eu/' title='Twitter' target='_blank' data-tag='GO_twitter'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/twitter.png' /></a>
			<a href='http://youtube.emmett.eu/' title='Youtube' target='_blank' data-tag='GO_youtube'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/youtube.png' /></a>
			<a href='http://soundcloud.emmett.eu/' title='SoundCloud' target='_blank' data-tag='GO_soundcloud'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/soundcloud.png' style='margin-bottom:5px;'/></a>
			<a href='http://myspace.emmett.eu/' title='MySpace' target='_blank' data-tag='GO_myspace'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/myspace.png' /></a>
			<a href='http://reverbnation.emmett.eu/' title='ReverbNation' target='_blank' data-tag='GO_reverbnation'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/reverbnation.png' style='width:55px;height:55px;margin-bottom:6px;'/></a>
			<a href='mailto:contact@emmett.eu' title='Contact' target='_blank' data-tag='GO_mail'><img src='<?php echo $this->baseUrl() ?>/img/fighting-fate-ep/mail.png'  style='width:60px;height:60px;margin-bottom:2px;'/></a>
		</div>
			
		<?php /*if (ENVIRONMENT == 'prod') : ?>
		<script type="text/javascript" src="<?php echo $this->version('fighting-fate-ep', 'js') ?>"></script>
		<?php else : */?>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/01.jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/02.three.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/03.tween.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/04.optimer_bold.typeface.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/05.ConvolutionShader.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/06.CopyShader.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/07.EffectComposer.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/08.RenderPass.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/09.BloomPass.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/10.ShaderPass.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/11.MaskPass.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/12.Detector.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/13.konami.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/js/99.init.js"></script>
		<?php /*endif;*/?>
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31404217-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	</body>
</html>
