<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->headTitle();
			echo $this->headMeta(); ?>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('fighting-fate-ep', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/fighting-fate-ep/css/01.global.css" />
		<?php endif; ?>
		<link rel="icon" href="<?php echo $this->baseUrl() ?>/favicon.gif" type="image/gif" />
	</head>
	<body>
		<p id="info"><?php echo tr("Sorry, we didn't take time to have this degraded version because our site is really cool on a recent browser (like <a href=\"http://www.google.com/chrome\">Chrome</a> ;))") ?></p>
	</body>
</html>