<div id="search">
	<h4>Recherche : </h4>
	<form action="#" method="post">
		<ul>
			<?php for ($i = 0; $i <= 10; $i++) : ?>
			<li id="search-<?php echo $i; ?>" <?php if ($i) echo 'style="display:none"'; ?> class="search-block">
				<ul>
					<li>
						<label for="fields">Champs : </label>
						<select multiple name="fields[<?php echo $i; ?>][]" size="<?php echo (count($this->cols) > 5) ? ceil(count($this->cols) / 1.5) : count($this->cols); ?>"/>
							<?php foreach ($this->cols as $colName) : ?>
								<?php if (!isset($this->config['forms']['delete'][$this->model]['elements'][$colName])) : ?>
									<option value="<?php echo $colName; ?>"><?php echo isset($this->config['forms'][$this->model]['elements'][$colName]['options']['label']) ? $this->config['forms'][$this->model]['elements'][$colName]['options']['label'] : $colName; ?></option>
								<?php endif; ?>
							<?php endforeach; ?>
						</select>
					</li>
					<li>
						<label for="func">Operateur : </label>
						<select type="text" name="func[<?php echo $i; ?>]"/>
							<?php foreach ($this->func as $value => $libelle) :?>
							<option value="<?php echo $value; ?>"><?php echo $libelle; ?></option>
							<?php endforeach; ?>
						</select>
					</li>
					<li><label for="query">Valeur : </label><input type="text" name="query[<?php echo $i; ?>]"/></li>
					<li>
						<a href="#" class="search-add">add</a>
						<?php if ($i) :?>
						<a href="#" class="search-del">remove</a>
						<?php endif; ?>
					</li>
				</ul>
			</li>
			<?php endfor; ?>
		</ul>
		<dl>
			<fieldset class="fieldset_submit">
				<input type="submit" value="Rechercher" name="submit">
			</fieldset>
		</dl>
	</form>
</div>
<script>
	$(".search-add").click(function(e) {
		$(this).parents(".search-block").next(".search-block").show("slow");
		e.preventDefault();
	});
	$(".search-del").click(function(e) {
		$(this).parents(".search-block").hide("slow");
		e.preventDefault();
	});
</script>