<div class="content">
	<h3>EMMETT</h3>
	<p>
	<?php echo tr('One summer evening in 2011, exactly on February 5, Cedric Cizaire plays with his instrument. No evil spirit, I mean his guitar!'); ?><br/>
	<?php echo tr('When suddenly, tired of playing his compositions alone like a dog, it takes the "want to want" to mount a rock band.') ?>
	</p>
	<p>
	<?php echo tr('Fate sends Jay Moulin, bassist emeritus, which will now be nicknamed "Zack de la Rochette" from the town where he\'s native.'); ?><br/>
	<?php echo tr('After weeks of harassment by mail, anonymous letters or parcel bombs, Maxime Guény, aka "Climax", pianist quality, finally agreed to do a test with the group. These 3 there will never be able to leave.'); ?>
	</p>
	<p>
	<?php echo tr('There remains to find a drummer. They find it totally by accident ... in his room. Romeo Valalik joined EMMETT.'); ?><br/>
	<?php echo tr('One year and a half, they released their first LP of 13 songs flavored air, rock and pop. More importantly, they find themselves in the final of Fallenfest at La Cigale! They\'re currently touring in France...'); ?>
	</p>
</div>