<div class="content">
	<h3>Roméo</h3>
	<p><?php echo tr("Author-songwriter and multi-instrumentalist, Romeo or \"Anythings\" is a member of three active groups: EMMETT, Needle Sharp and Falling in The Sky.") ?></p>
	<p><?php echo tr("He starts the conservatory at a young age with percussion, piano and singing, but stops seven years later because, well, honestly, music theory, it is pain in the ass! And it was not until two years later that he will (re)do drums, guitar then bass, and then piano, and then accordion, but in a more rock style this time.") ?></p>
	<p><?php echo tr("Besides that, it is the writer-director of a web-series called \"FreeStyle\", he played in a few short films and is the official editor of EMMETT!") ?></p>
	<p><?php echo tr("As he concludes himself \"In short, my real name is Romeo Valalik-Besserve and ... I do a lot of things.\"") ?></p>
	<p><a href="http://anythingsinthesky.com">Anythingsinthesky.com</a></p>
</div>