<?php echo $this->doctype() ?>
<html>
	<head>
		<?php echo $this->headTitle();
			echo $this->headMeta(); ?>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('first-aid', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/01.cover.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/02.disk.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/03.zen.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/04.style.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/05.coin-slider-styles.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/06.member.css" />		
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/07.news.css" />		
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/08.mediaqueries.css" />		
		<?php endif; ?>
		<link rel="icon" href="<?php echo $this->baseUrl() ?>/favicon.gif" type="image/gif" />
		<!--link rel="alternate" type="application/rss+xml" title="<?php echo tr('EMMETT Latest News')?> (RSS)" href="http://www.emmett.eu/rss" />
		<link rel="alternate" type="application/atom+xml" title="<?php echo tr('EMMETT Latest News')?> (Atom)" href="http://www.emmett.eu/atom" /-->
	</head>
	<body>
		<div id='menu'>
			<ul>
				<!--li>
					<a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'news', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'news') ?>'><?php echo tr('News')?></a>
				</li-->
				<li>
					<a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'band') ?>'><?php echo tr('Band')?></a>
					<ul>
						<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'band') ?>'>EMMETT</a></li>
						<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid', 'member' => 'cedric'), 'band') ?>'>Cédric CIZAIRE</a></li>
						<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid', 'member' => 'jay'), 'band') ?>'>Jay MOULIN</a></li>
						<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid', 'member' => 'maxime'), 'band') ?>'>Maxime GUÉNY</a></li>
						<li><a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'band', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid', 'member' => 'romeo'), 'band') ?>'>Roméo VALALIK BESSERVE</a></li>
					</ul>
				</li>
				<li>
					<a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'album', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'front') ?>'><?php echo tr('Album') ?></a>
				</li>
				<li>
					<a href='<?php echo $this->url(array('controller' => 'misc', 'action' => 'index', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'front') ?>'><?php echo tr('Misc')?></a>
					<ul>
						<li><a href='<?php echo $this->url(array('controller' => 'misc', 'action' => 'lyrics', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid')) ?>'><?php echo tr('Lyrics') ?></a></li>
						<li><a href='<?php echo $this->url(array('controller' => 'misc', 'action' => 'tab', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid')) ?>'><?php echo tr('Bass tabs') ?></a></li>
					</ul>
				</li>
					<!--li>
						<a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'store', 'lang' => Zend_Registry::getInstance()->locale, 'module' => 'first-aid'), 'store') ?>'><?php echo tr('Store')?></a>
					</li-->
			</ul>
			<div id='locale'>
				<a href='<?php echo $this->url(array('lang' => 'fr')) ?>' rel='nolink'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/lang_fr.png' /></a>
				<a href='<?php echo $this->url(array('lang' => 'en')) ?>' rel='nolink'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/lang_en.png' /></a>
			</div>
		</div>
		<canvas id="starfield"></canvas>
		
		<div id='content'>
			<?php echo $this->layout()->content ?>
		</div>
		
		<div style='display:none;' id='zencase'>
			<div id="zen">
				<span class="circle"></span>
				<span class="progress"></span>
				<span class="buffer"></span>
				<span class="drag"></span>
				<div class="button">
					<span class="icon play"></span>
					<span class="icon pause"></span>
				</div>
			</div>
		</div>
		<div style='display:none'>
			<?php $albums = Emmett_Model_Albums::get('First Aid');?>
			<div class='back'>
				<p class='tracks'>
					<?php foreach ($albums['tracks'] as $title => $track) :?>
						<a href="<?php echo $this->baseUrl() ?>/<?php echo $track['ogg']?>" style='<?php echo $track['style']?>' rel='nolink' title="<?php echo $title ?>" data-tag="Track_<?php echo str_replace(' ', '_', $title) ?>"></a>
					<?php endforeach; ?>
				</p>
			</div>
		</div>
		<span class="player"></span>
		
		<div id='soundstar'>
			<h1 id='title'>Leaving</h1>
			<div>
				<a href='#' id='soundplay' title='Play'  rel='nolink' style='display:none;' data-tag='Sound_play'>&#x21;</a>
				<a href='#' id='soundpause' title='Pause'  rel='nolink' data-tag='Sound_pause'>&#x22;</a>
				<a href='#' id='soundrandom' title='Random' rel='nolink' data-tag='Sound_random'>&#x23;</a>
			</div>
		</div>
		<div id='donate'>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target='_blank'>
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="Y64LAX2HZQQBJ">
				<?php if ($this->layout()->locale == 'fr') : ?>
				<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
				<?php else : ?>
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<?php endif; ?>
				<img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
			</form>
		</div>
		<div id='nyan' style='display:none;'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/nyan.gif' /></div>
		<div id='footer'>
			<a href='http://facebook.emmett.eu/' title='Facebook' target='_blank' data-tag='GO_facebook'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' /></a>
			<a href='http://twitter.emmett.eu/' title='Twitter' target='_blank' data-tag='GO_twitter'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' /></a>
			<a href='http://youtube.emmett.eu/' title='Youtube' target='_blank' data-tag='GO_youtube'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/youtube.png' /></a>
			<a href='http://soundcloud.emmett.eu/' title='SoundCloud' target='_blank' data-tag='GO_soundcloud'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/soundcloud.png' style='margin-bottom:5px;'/></a>
			<a href='http://myspace.emmett.eu/' title='MySpace' target='_blank' data-tag='GO_myspace'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/myspace.png' /></a>
			<a href='http://reverbnation.emmett.eu/' title='ReverbNation' target='_blank' data-tag='GO_reverbnation'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/reverbnation.png' style='width:55px;height:55px;margin-bottom:6px;'/></a>
			<a href='mailto:contact@emmett.eu' title='Contact' target='_blank' data-tag='GO_mail'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/mail.png'  style='width:60px;height:60px;margin-bottom:2px;'/></a>
		</div>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<?php if (ENVIRONMENT == 'prod') : ?>
		<script type="text/javascript" src="<?php echo $this->version('first-aid', 'js') ?>"></script>
		<?php else : ?>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/01.jquery-css-transform.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/02.rotate3Di.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/03.jquery.rotate.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/04.jquery.grab.js"></script> 
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/05.jquery.jplayer.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/06.jquery.textshadow.animate.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/07.carousel.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/08.zen.js"></script>	
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/09.starfield.js"></script>	
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/10.konami.js"></script>	
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/11.jquery.tools.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/12.coin-slider.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/13.lib.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/lib/first-aid/js/14.history.js"></script>
		<?php endif;?>
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31404217-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	</body>
</html>
