<!doctype html>
<html>
	<head>
		<title>EMMETT | <?php echo tr('Compatibility') ?></title>
		<meta charset="UTF-8">
		<meta name="robots" content="noindex,nofollow">
		<meta property="og:title" content="<?php echo tr('Something new is coming...') ?>">
		<meta property="og:url" content="http://<?php echo $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']?>">
		<meta property="og:image" content="http://<?php echo $_SERVER['SERVER_NAME'] ?>/img/first-aid/sharefb.png">
		<meta property="og:description" content="<?php echo tr('.. and you can find out what by discovering this website...') ?>">
		

		<?php if (ENVIRONMENT == 'prod') : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->version('first-aid', 'css') ?>" />
		<?php else : ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/01.cover.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/02.disk.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/03.zen.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/04.style.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/lib/first-aid/css/05.member.css" />
		<?php endif; ?>
		<?php if ($this->redirect) : ?>
			<meta HTTP-EQUIV="REFRESH" content="0; url=<?php echo $this->url(array('module' => 'first-aid', 'action' => 'index', 'controller' => 'index'), 'front') ?>">
		<?php endif; ?>
	</head>
	<body>
		<div id='content'>
			<div id='full'>
			<p>
				<?php echo tr('Your browser does not seem compatible to fully enjoy the EMMETT\'s website experience. We suggest you to use <a href="http://www.google.com/chrome">Chrome</a>.') ?>
			</p>
			<p>
				<?php printf(tr('You are actually using %s version %s'), $this->device->getBrowser(), $this->device->getBrowserVersion()); ?>
			</p>
			<p>
				<?php echo tr('Would you like to see the site in a degraded compatible version?') ?>
			</p>
			<a href="<?php echo $this->url(array('decision' => 'no', 'module' => 'first-aid', 'controller' => 'index', 'action' => 'advice'), 'front') ?>" class="left"><?php echo tr('no') ?></a>
			<a href="<?php echo $this->url(array('decision' => 'yes', 'module' => 'first-aid', 'controller' => 'index', 'action' => 'advice'), 'front') ?>" class="right"><?php echo tr('yes') ?></a>
			</div>
		</div>
	</body>
</html>
