<table>
	<tr>
		<td>
			<h2>Cédric&nbsp;CIZAIRE</h2>
		</td>
		<td class="social">
			<a href='http://www.twitter.com/Cizaire' target='_blank' class="left" data-tag='cedric_twitter'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' style='width:32px;height:32px;'/></a>
			<a href='http://www.facebook.com/cedriccizairesing' target='_blank' class="left" data-tag='cedric_facebook'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' style='width:32px;height:32px;'/></a>
			<a href='mailto:cedric@emmett.eu' target='_blank' class="left" data-tag='cedric_mail'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/mail.png' style='width:32px;height:32px;'/></a>
		</td>
	</tr>
	<tr>
		<td>
			<div id='cedric_photos'>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/cedric.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/cedric-2.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/cedric-3.jpg' /></a>
			</div>
		</td>
		<td class="description">
			<p>
			<?php echo tr('2011 was a year of turning points for Cedric, aka the Dabbler. First, he had 30 years but more importantly,he established the world record of chocolate "Sundaes Bloody Sundaes" eatingness. But that\'s not the point.'); ?><br/>
			<?php echo tr('This  militant Avignoner especially decided to materialize an idea that he can’t get his head off for at least a week: form a rock band. His compositions making his labrador crying, he said it might work with the fairer sex.') ?>
			</p>
			<p>
			<?php echo tr('His voice, his guitar and him felt ready to come into contact with the outside world, providence, or the internet, call it whatever you want, enabled him to meet with the three best players from the capital!'); ?><br/>
			<?php echo tr('In addition, it has for several years a comedy career that allowed him to be a columnist on Europe 1 this past summer to conduct a significant number of passages shows, working with Pierre Palmade, but also to tread many theater with his One Man Show: SING, SKETCH and F***'); ?>
			</p>
			<p>
			<?php echo tr('This comic-musical performance has also acted as a trigger in Cedric’s desire to engage in "serious" texts and songs. After mimicing Coluche, it is now for Tom Morello! In concert, he’ll never restrain to make the public  sing but also  making it laugh!'); ?>
			</p>
		</td>
	</tr>
</table>