<table>
	<tr>
		<td>
			<h2>Jay&nbsp;MOULIN</h2>
		</td>
		<td class='social'>
			<a href='http://www.youtube.com/user/jaymoulin' target='_blank' class="left" data-tag='jay_youtube'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/youtube.png'  style='width:32px;height:32px;'/></a>
			<a href='http://www.twitter.com/numer07' target='_blank' class="left" data-tag='jay_twitter'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' style='width:32px;height:32px;'/></a>
			<a href='http://www.facebook.com/jaymoulin' target='_blank' class="left" data-tag='jay_facebook'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' style='width:32px;height:32px;'/></a>
			<a href='mailto:jay@emmett.eu' target='_blank' class="left" data-tag='jay_mail'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/mail.png' style='width:32px;height:32px;'/></a>
		</td>
	</tr>
	<tr>
		<td>
			<div id='jay_photos'>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/jay.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/jay-2.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/jay-3.jpg' /></a>
			</div>
		</td>
		<td class="description">
			<p>
			<?php echo tr('Born in 85, Jay began to make electronic music with samples first and then his own compositions'); ?><br/>
			<?php echo tr('At the age of 21, he was spotted by the guitarist of the rock / metal band "<a href="http://www.myspace.com/fewze" data-tag="fewze">Fewze</a>" and became the lead singer.') ?>
			</p>
			<p>
			<?php echo tr('In 2008, Jay started his own web development company "<a href="#" class="tip" id="jay_femtopixel" data-tag="femtopixel">FemtoPixel</a>" with which he developed the social network "<a href="#" class="tip" id="jay_doonoyz" data-tag="doonoyz">Doonoyz</a>" for an online band creation and artistic promulgation purpose.'); ?><br/>
			<?php echo tr('Unfortunately, the lack of communication about the platform led him to convert "Doonoyz" into a band support association.'); ?>
			</p>
			<p>
			<?php echo tr('At the split of "Fewze", Jay teaches himself bass in early 2011 and will join six months later, by browsing the ads,  the punk / rock band "<a href="#" class="tip" id="jay_monsters_ahead" data-tag="monstersahead">Monsters&nbsp;Ahead</a>" (wich nicknamed him "numéro 7"), first as a singer, then as a bass player; the metal band "<a href="http://www.facebook.com/DreamThiefMusic" data-tag="dreamthief">Dream Thief</a>", formed with Romeo VALALIK Besserve; and EMMETT.'); ?><br/>
			<?php echo tr('Described himself as an hyperactive schizophrenic because of its many activities, he is a fan of retro gaming, sleeps an average of 5 hours per night, loves to hide Konami Code in websites he develops, can do the mayo and no one knows if he is really left or right handed...'); ?>
			</p>
				
				<div id='tip_jay_monsters_ahead' class='tooltip'>
					<a href='http://www.facebook.com/Monstersahead' target='_blank'  data-tag="monstersahead_facebook"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' /></a>
					<a href='https://www.youtube.com/user/monstersahead' target='_blank'  data-tag="monstersahead_youtube"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/youtube.png' /></a>
				</div>
				
				<div id='tip_jay_doonoyz' class='tooltip'>
					<a href='http://www.facebook.com/Doonoyz' target='_blank'  data-tag="doonoyz_facebook"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' /></a>
					<a href='http://www.twitter.com/Doonoyz' target='_blank'  data-tag="doonoyz_twitter"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' /></a>
				</div>
				
				<div id='tip_jay_femtopixel' class='tooltip'>
					<a href='http://www.facebook.com/FemtoPixel' target='_blank'  data-tag="femtopixel_facebook"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' /></a>
					<a href='http://www.twitter.com/moulinjay' target='_blank'  data-tag="femtopixel_twitter"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' /></a>
				</div>
		</td>
	</tr>
</table>