<table>
	<tr>
		<td>
			<h2>Maxime&nbsp;GUÉNY</h2>
		</td>
		<td class='social'>
			<a href='http://www.twitter.com/tvmedias' target='_blank' class="left" data-tag="maxime_twitter"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' style='width:32px;height:32px;'/></a>
			<a href='mailto:maxime@emmett.eu' target='_blank' class="left" data-tag="maxime_mail"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/mail.png' style='width:32px;height:32px;'/></a>
		</td>
	</tr>
	<tr>
		<td>
			<div id='maxime_photos'>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/maxime.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/maxime-2.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/maxime-3.jpg' /></a>
			</div>
		</td>
		<td class="description">
			<p>
			<?php echo tr('Intrigued by many artistic fields since childhood, Maxime has rapidly launched into learning the piano and synthesizer at the age of 7 years.'); ?><br/>
			<?php echo tr('In parallel, another consuming passion has added to his hobbies, it\'s magic. Cards, balls and other close-up tricks still continue to occupy its activities.') ?>
			</p>
			<p>
			<?php echo tr('After integrating over four years the circus school " Aux Agrès du Vent" located around Châlons-en-Champagne, he started to ensure the presentation of more than a dozen cabarets and circus performers galas.'); ?><br/>
			<?php echo tr('The madness of the scene then quickly grabbed him by integrating the professional theater company "La Compagnie des Gens" in Côte d\'Or.'); ?>
			</p>
			<p>
			<?php echo tr('Wishing to discover new scenic asperities, he landed his first role in a musical, then he continued - as part of his studies - to specialize in first audiovisual in cinema, only to discover the specifics of information and communication sciences.'); ?><br/>
			<?php echo tr('Sewing up he became a journalist media, which does not prevent him to practice - to varying degrees - each of the arts mentioned above.'); ?>
			</p>
		</td>
	</tr>
</table>