<table>
	<tr>
		<td>
			<h2>Roméo&nbsp;VALALIK&nbsp;BESSERVE</h2>
		</td>
		<td class='social'>
			<a href='http://www.facebook.com/profile.php?id=1301906790' target='_blank' class="left" data-tag="romeo_facebook"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' style='width:32px;height:32px;'/></a>
			<a href='http://www.twitter.com/Romeo_Valalik' target='_blank' class="left" data-tag='romeo_twitter'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/twitter.png' style='width:32px;height:32px;'/></a>
			<a href='http://www.youtube.com/user/ROMENOCH39' target='_blank' class="left" data-tag="romeo_youtube"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/youtube.png' style='width:32px;height:32px;'/></a>
			<a href='mailto:romeo@emmett.eu' target='_blank' class="left"  data-tag="romeo_mail"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/mail.png' style='width:32px;height:32px;'/></a>
		</td>
	</tr>
	<tr>
		<td>
			<div id='romeo_photos'>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/romeo.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/romeo-2.jpg' /></a>
				<a href='#'><img src='<?php echo $this->baseUrl() ?>/img/first-aid/member/romeo-3.jpg' /></a>
			</div>
		</td>
		<td class="description">
			<p>
			<?php echo tr('Roméo began percussions at the Conservatory when he was 8. He stayed there for 7 years, until his desire to rock and roll took over. It will then form a first band where he\'ll hold the position of singer-drummer, then a second and even a third before joining EMMETT as drummer. This will be a breakthrough for him as it is with this band that he will make his first gig, a first at La Scène Bastille and then at La Cigale! That is what we call a Usain Bolt start!'); ?>
			</p>
			<p>
			<?php echo tr('Today all these bands still exist, "<a href="#" class="tip" id="romeo_sweet_memories"  data-tag="sweetmemories">Sweet&nbsp;Memories</a>", "<a href="http://www.facebook.com/DreamThiefMusic"  data-tag="dreamthief">Dream Thief</a>" and "Falling in the Sky", that he hopes to raise them as high as possible ... and so for EMMETT of course!'); ?>
			</p>
			<div class='tooltip' id='tip_romeo_sweet_memories'>
				<a href='http://www.facebook.com/pages/Sweet-Memories/172904499422653' target='_blank' data-tag="sweetmemories_facebook"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/facebook.png' /></a>
				<a href='http://www.youtube.com/user/SweetMemoriesMusic' target='_blank' data-tag="sweetmemories_youtube"><img src='<?php echo $this->baseUrl() ?>/img/first-aid/youtube.png' /></a>
			</div>
		</td>
	</tr>
</table>